### ISSUE TITLE
error stops Create Missing Brace Layers in Components.py from running

### ISSUE THREAD

**Issue by xotypeco** [yanone/Yanone-GlyphsApp-Scripts#1]
this happens reliably in each glyph it's trying to create a brace layer in:

Start
Traceback (most recent call last):
  File "Create Missing Brace Layers in Components.py", line 59, in <module>
    newLayer.reinterpolate()
  File "GlyphsApp/GlyphsApp/__init__.py", line 6574, in Layer_replaceLayerWithInterpolation
ValueError: NSInvalidArgumentException - -[GSInstance instanceInterpolations:axesCount:]: unrecognized selector sent to instance 0x6000037fe5b0
End

**Comment by xotypeco** [comment]
update: I solved this, so I'm closing it. in Big Shoulders, all the brace layers between Text Thin and Text Black were called {300,10} except for one brace in uppercase M, where I had hit the zero key one too many times, so the brace was called {300,100). once I corrected that to test, the script did what was expected.
